import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es-mx';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'search.placeholder': 'Search games...',
    'games.all': 'All Games',
    'games.available': 'games available',
    'games.none': 'No games found',
    'games.none.desc': "We couldn't find any games matching \"{query}\" in this category. Try a different search term.",
    'games.loading': 'Loading {title}...',
    'player.open': 'Open in new tab',
    'player.fullscreen': 'Fullscreen',
    'player.close': 'Close game',
    'nav.home': 'Home',
    'nav.games': 'Games',
    'nav.store': 'Store',
    'nav.quests': 'Quests',
    'nav.achievements': 'Achievements',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.roadmap': 'Roadmap',
    'nav.daily': 'Daily Rewards',
    'nav.menu': 'Menu',
    'nav.categories': 'Categories',
    'footer.title': 'Unblocked Games',
    'footer.desc': 'Play 100+ games anywhere, anytime.',
    'cat.all': 'All Games',
    'cat.action': 'Action',
    'cat.sandbox': 'Sandbox',
    'cat.clicker': 'Clicker',
    'cat.puzzle': 'Puzzle',
    'cat.sports': 'Sports',
    'cat.io': 'IO Games',
    'cat.iogames': 'IO Games',
    'cat.classics': 'Classics',
    'cat.strategy': 'Strategy',
    'cat.racing': 'Racing',
    'cat.asmr': 'ASMR',
    'cat.papas': "Papa's",
    'cat.fun': 'Fun',
    'cat.adventure': 'Adventure',
    'cat.arcade': 'Arcade',
    'cat.simulation': 'Simulation',
    'store.title': 'Neon Store',
    'store.desc': 'Spend your hard-earned coins on exclusive upgrades.',
    'store.mystery': 'Mystery Boxes',
    'store.snake': 'Snake Skin Box',
    'store.snake.desc': 'Unlock exclusive skins for the Neon Snake game. Guarantees a skin you don\'t already own!',
    'store.open': 'Open for {cost} Coins',
    'store.unlocked': 'Unlocked: {item}',
    'store.cosmetics': 'Cosmetics & Perks',
    'store.owned': 'Owned',
    'store.item.streak-freeze.name': 'Streak Freeze',
    'store.item.streak-freeze.desc': 'Miss a day? Your streak will be saved automatically.',
    'store.item.neon-theme.name': 'Neon Glow Theme',
    'store.item.neon-theme.desc': 'Unlock a premium fuchsia neon glow for all game cards.',
    'store.item.emerald-theme.name': 'Emerald Theme',
    'store.item.emerald-theme.desc': 'Unlock a lush green theme for your profile.',
    'store.item.ruby-theme.name': 'Ruby Theme',
    'store.item.ruby-theme.desc': 'Unlock a deep red theme for your profile.',
    'store.item.golden-crown.name': 'Golden Crown',
    'store.item.golden-crown.desc': 'Show off your wealth with a golden crown next to your streak.',
    'store.item.diamond-crown.name': 'Diamond Crown',
    'store.item.diamond-crown.desc': 'The ultimate flex. A diamond crown for the elite.',
    'store.item.vip-badge.name': 'VIP Badge',
    'store.item.vip-badge.desc': 'Exclusive VIP status icon on your profile.',
    'store.item.glitch-fx.name': 'Glitch FX',
    'store.item.glitch-fx.desc': 'Add a cyberpunk glitch effect to your avatar.',
    'quests.title': 'Quests',
    'quests.desc': 'Complete objectives to earn coins.',
    'quests.daily': 'Daily Quests',
    'quests.weekly': 'Weekly Quests',
    'quests.claimed': 'Claimed',
    'quests.claim': 'Claim Reward',
    'quests.progress': 'In Progress',
    'achievements.title': 'Achievements',
    'achievements.desc': 'Unlock milestones to earn massive coin rewards.',
    'achievements.unlocked': 'UNLOCKED',
    'achievements.claimed': 'CLAIMED',
    'achievements.claim': 'Claim',
    'achievements.locked': 'Locked',
    'ach.first-blood.title': 'First Blood',
    'ach.first-blood.desc': 'Play your first game',
    'ach.gamer.title': 'Gamer',
    'ach.gamer.desc': 'Play 10 games total',
    'ach.addicted.title': 'Addicted',
    'ach.addicted.desc': 'Play 50 games total',
    'ach.master.title': 'Arcade Master',
    'ach.master.desc': 'Play 100 games total',
    'ach.grandmaster.title': 'Grandmaster',
    'ach.grandmaster.desc': 'Play 500 games total',
    'ach.dedicated.title': 'Dedicated',
    'ach.dedicated.desc': 'Reach a 3-day streak',
    'ach.weekly-warrior.title': 'Weekly Warrior',
    'ach.weekly-warrior.desc': 'Reach a 7-day streak',
    'ach.fortnight-fanatic.title': 'Fortnight Fanatic',
    'ach.fortnight-fanatic.desc': 'Reach a 14-day streak',
    'ach.monthly-legend.title': 'Monthly Legend',
    'ach.monthly-legend.desc': 'Reach a 30-day streak',
    'ach.quarterly-king.title': 'Quarterly King',
    'ach.quarterly-king.desc': 'Reach a 90-day streak',
    'ach.sports-fan.title': 'Sports Fan',
    'ach.sports-fan.desc': 'Play 5 Sports games',
    'ach.sports-pro.title': 'Sports Pro',
    'ach.sports-pro.desc': 'Play 15 Sports games',
    'ach.action-novice.title': 'Action Novice',
    'ach.action-novice.desc': 'Play 5 Action games',
    'ach.action-expert.title': 'Action Expert',
    'ach.action-expert.desc': 'Play 25 Action games',
    'ach.puzzle-novice.title': 'Puzzle Novice',
    'ach.puzzle-novice.desc': 'Play 5 Puzzle games',
    'ach.puzzle-expert.title': 'Puzzle Expert',
    'ach.puzzle-expert.desc': 'Play 25 Puzzle games',
    'ach.clicker-novice.title': 'Clicker Novice',
    'ach.clicker-novice.desc': 'Play 3 Clicker games',
    'ach.clicker-addict.title': 'Clicker Addict',
    'ach.clicker-addict.desc': 'Play 10 Clicker games',
    'ach.io-novice.title': 'IO Novice',
    'ach.io-novice.desc': 'Play 5 IO Games',
    'ach.io-pro.title': 'IO Pro',
    'ach.io-pro.desc': 'Play 20 IO Games',
    'ach.chefs-apprentice.title': "Chef's Apprentice",
    'ach.chefs-apprentice.desc': "Play 2 Papa's games",
    'ach.head-chef.title': 'Head Chef',
    'ach.head-chef.desc': "Play all 6 Papa's games",
    'ach.classics-fan.title': 'Classics Fan',
    'ach.classics-fan.desc': 'Play 3 Classics games',
    'ach.sandbox-explorer.title': 'Sandbox Explorer',
    'ach.sandbox-explorer.desc': 'Play a Sandbox game',
    'ach.asmr-addict.title': 'ASMR Addict',
    'ach.asmr-addict.desc': 'Play 2 ASMR games',
    'ach.wealthy.title': 'Wealthy',
    'ach.wealthy.desc': 'Accumulate 1,000 coins',
    'ach.rich.title': 'High Roller',
    'ach.rich.desc': 'Accumulate 5,000 coins',
    'ach.millionaire.title': 'Millionaire',
    'ach.millionaire.desc': 'Accumulate 10,000 coins',
    'ach.collector.title': 'Collector',
    'ach.collector.desc': 'Buy 3 items from the store',
    'ach.hoarder.title': 'Hoarder',
    'ach.hoarder.desc': 'Buy 10 items from the store',
    'level.5.title': 'Novice Explorer',
    'level.10.title': 'Apprentice Gamer',
    'level.25.title': 'Seasoned Veteran',
    'level.50.title': 'Arcade Master',
    'level.75.title': 'Grand Champion',
    'level.100.title': 'Legendary Status',
    'level.200.title': 'Mythic Entity',
    'level.300.title': 'Divine Being',
    'level.400.title': 'Cosmic Overlord',
    'level.500.title': 'Universal Creator',
    'quest.daily-play-3.title': 'Warmup',
    'quest.daily-play-3.desc': 'Play 3 games today',
    'quest.daily-play-10.title': 'Marathon',
    'quest.daily-play-10.desc': 'Play 10 games today',
    'quest.daily-action-2.title': 'Action Hero',
    'quest.daily-action-2.desc': 'Play 2 Action games today',
    'quest.daily-puzzle-2.title': 'Puzzle Master',
    'quest.daily-puzzle-2.desc': 'Play 2 Puzzle games today',
    'quest.daily-sports-2.title': 'Athlete',
    'quest.daily-sports-2.desc': 'Play 2 Sports games today',
    'quest.daily-clicker-1.title': 'Click Frenzy',
    'quest.daily-clicker-1.desc': 'Play 1 Clicker game today',
    'quest.daily-io-2.title': 'Online Warrior',
    'quest.daily-io-2.desc': 'Play 2 IO Games today',
    'quest.daily-papas-1.title': "Papa's Helper",
    'quest.daily-papas-1.desc': "Play a Papa's game today",
    'quest.weekly-play-25.title': 'Weekend Warrior',
    'quest.weekly-play-25.desc': 'Play 25 games this week',
    'quest.weekly-streak-5.title': 'Consistent Gamer',
    'quest.weekly-streak-5.desc': 'Reach a 5-day streak',
    'quest.weekly-action-10.title': 'Action Fanatic',
    'quest.weekly-action-10.desc': 'Play 10 Action games this week',
    'quest.weekly-puzzle-10.title': 'Big Brain',
    'quest.weekly-puzzle-10.desc': 'Play 10 Puzzle games this week',
    'quest.weekly-sports-7.title': 'League MVP',
    'quest.weekly-sports-7.desc': 'Play 7 Sports games this week',
    'quest.weekly-clicker-5.title': 'Clicker Legend',
    'quest.weekly-clicker-5.desc': 'Play 5 Clicker games this week',
    'quest.weekly-io-8.title': 'IO Dominator',
    'quest.weekly-io-8.desc': 'Play 8 IO Games this week',
    'quest.weekly-papas-3.title': "Papa's Regular",
    'quest.weekly-papas-3.desc': "Play 3 Papa's games this week",
    'profile.title': 'Profile',
    'profile.lvl': 'Level',
    'profile.xp': 'XP',
    'profile.streak': 'Current Streak',
    'profile.coins': 'Total Coins',
    'profile.played': 'Games Played',
    'profile.daily': 'Daily Reward',
    'profile.claim': 'Claim Now',
    'profile.claimed': 'Claimed',
    'profile.skins': 'Active Skins',
    'profile.snake': 'Neon Snake',
    'profile.snake.desc': 'Select your equipped skin for the Snake game.',
    'profile.badges': 'Achievement Badges',
    'profile.badges.none': 'No Badges Yet',
    'profile.badges.none.desc': 'Play games and complete achievements to earn badges!',
    'profile.redeem': 'Redeem Code',
    'profile.data': 'Data Management',
    'profile.export': 'Export Save',
    'profile.export.desc': 'Export your save data to keep your progress if you host this website elsewhere.',
    'profile.import': 'Import Save',
    'profile.save': 'Save Profile',
    'profile.edit': 'Edit Profile',
    'profile.prestige': 'Prestige',
    'profile.owner': 'Owner',
    'profile.admin': 'Admin',
    'profile.days': 'Days',
    'profile.multiplier': 'MULTIPLIER',
    'header.lvl': 'LVL',
    'header.coins': 'Coins',
    'header.streak': 'Daily Streak',
    'header.multiplier': 'Multiplier',
    'header.rewards': 'Click for Rewards',
    'header.roadmap': 'Roadmap',
    'header.quests': 'Quests',
    'header.achievements': 'Achievements',
    'header.store': 'Store',
    'header.profile': 'Profile',
    'lang.english': 'English',
    'lang.spanish': 'Español (MX)',
    'roadmap.title': 'Progression Roadmap',
    'roadmap.desc': 'Level up to unlock exclusive rewards and titles.',
    'roadmap.current': 'Current Level',
    'roadmap.next': 'Next Level',
    'roadmap.prestige.avail': 'Prestige Available!',
    'roadmap.prestige.desc': 'Reset your level to 1 and gain a Prestige rank.',
    'roadmap.prestige.confirm': 'Are you sure you want to Prestige? This will reset your level and XP to 1, but you will gain a Prestige rank!',
    'roadmap.prestige.now': 'Prestige Now',
    'roadmap.level': 'Level',
    'roadmap.claim': 'Claim Reward',
    'roadmap.claimed': 'Claimed',
    'roadmap.locked': 'Locked',
    'daily.title': 'Daily Rewards',
    'daily.desc': 'Keep your streak alive to multiply your daily coins!',
    'daily.streak': 'Current Streak',
    'daily.multiplier': 'Current Multiplier',
    'daily.claim': 'Claim Daily Reward',
    'daily.claimed.msg': 'Daily reward claimed!',
    'daily.tomorrow': 'Come back tomorrow!',
    'daily.upcoming': 'Upcoming Rewards',
    'daily.day': 'Day',
    'daily.available': 'Available Now!',
  },
  'es-mx': {
    'search.placeholder': 'Buscar juegos...',
    'games.all': 'Todos los Juegos',
    'games.available': 'juegos disponibles',
    'games.none': 'No se encontraron juegos',
    'games.none.desc': "No pudimos encontrar ningún juego que coincida con \"{query}\" en esta categoría. Intenta con otro término de búsqueda.",
    'games.loading': 'Cargando {title}...',
    'player.open': 'Abrir en nueva pestaña',
    'player.fullscreen': 'Pantalla completa',
    'player.close': 'Cerrar juego',
    'nav.home': 'Inicio',
    'nav.games': 'Juegos',
    'nav.store': 'Tienda',
    'nav.quests': 'Misiones',
    'nav.achievements': 'Logros',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.roadmap': 'Hoja de Ruta',
    'nav.daily': 'Recompensas Diarias',
    'nav.menu': 'Menú',
    'nav.categories': 'Categorías',
    'footer.title': 'Juegos Desbloqueados',
    'footer.desc': 'Juega más de 100 juegos en cualquier lugar y momento.',
    'cat.all': 'Todos los Juegos',
    'cat.action': 'Acción',
    'cat.sandbox': 'Sandbox',
    'cat.clicker': 'Clicker',
    'cat.puzzle': 'Puzzle',
    'cat.sports': 'Deportes',
    'cat.io': 'Juegos IO',
    'cat.iogames': 'Juegos IO',
    'cat.classics': 'Clásicos',
    'cat.strategy': 'Estrategia',
    'cat.racing': 'Carreras',
    'cat.asmr': 'ASMR',
    'cat.papas': 'Papa',
    'cat.fun': 'Diversión',
    'cat.adventure': 'Aventura',
    'cat.arcade': 'Arcade',
    'cat.simulation': 'Simulación',
    'store.title': 'Tienda Neón',
    'store.desc': 'Gasta tus monedas ganadas con esfuerzo en mejoras exclusivas.',
    'store.mystery': 'Cajas Misteriosas',
    'store.snake': 'Caja de Skins de Snake',
    'store.snake.desc': 'Desbloquea skins exclusivas para el juego Neon Snake. ¡Garantiza una skin que no tengas!',
    'store.open': 'Abrir por {cost} Monedas',
    'store.unlocked': 'Desbloqueado: {item}',
    'store.cosmetics': 'Cosméticos y Ventajas',
    'store.owned': 'Obtenido',
    'store.item.streak-freeze.name': 'Congelador de Racha',
    'store.item.streak-freeze.desc': '¿Perdiste un día? Tu racha se guardará automáticamente.',
    'store.item.neon-theme.name': 'Tema de Brillo Neón',
    'store.item.neon-theme.desc': 'Desbloquea un brillo de neón fucsia premium para todas las tarjetas de juegos.',
    'store.item.emerald-theme.name': 'Tema Esmeralda',
    'store.item.emerald-theme.desc': 'Desbloquea un exuberante tema verde para tu perfil.',
    'store.item.ruby-theme.name': 'Tema Rubí',
    'store.item.ruby-theme.desc': 'Desbloquea un tema rojo intenso para tu perfil.',
    'store.item.golden-crown.name': 'Corona Dorada',
    'store.item.golden-crown.desc': 'Muestra tu riqueza con una corona dorada junto a tu racha.',
    'store.item.diamond-crown.name': 'Corona de Diamante',
    'store.item.diamond-crown.desc': 'La máxima demostración. Una corona de diamante para la élite.',
    'store.item.vip-badge.name': 'Insignia VIP',
    'store.item.vip-badge.desc': 'Icono exclusivo de estado VIP en tu perfil.',
    'store.item.glitch-fx.name': 'Efecto Glitch',
    'store.item.glitch-fx.desc': 'Añade un efecto de falla cyberpunk a tu avatar.',
    'quests.title': 'Misiones',
    'quests.desc': 'Completa objetivos para ganar monedas.',
    'quests.daily': 'Misiones Diarias',
    'quests.weekly': 'Misiones Semanales',
    'quests.claimed': 'Reclamado',
    'quests.claim': 'Reclamar Recompensa',
    'quests.progress': 'En Progreso',
    'achievements.title': 'Logros',
    'achievements.desc': 'Desbloquea hitos para ganar recompensas masivas de monedas.',
    'achievements.unlocked': 'DESBLOQUEADO',
    'achievements.claimed': 'RECLAMADO',
    'achievements.claim': 'Reclamar',
    'achievements.locked': 'Bloqueado',
    'ach.first-blood.title': 'Primera Sangre',
    'ach.first-blood.desc': 'Juega tu primer juego',
    'ach.gamer.title': 'Jugador',
    'ach.gamer.desc': 'Juega 10 juegos en total',
    'ach.addicted.title': 'Adicto',
    'ach.addicted.desc': 'Juega 50 juegos en total',
    'ach.master.title': 'Maestro de Arcade',
    'ach.master.desc': 'Juega 100 juegos en total',
    'ach.grandmaster.title': 'Gran Maestro',
    'ach.grandmaster.desc': 'Juega 500 juegos en total',
    'ach.dedicated.title': 'Dedicado',
    'ach.dedicated.desc': 'Alcanza una racha de 3 días',
    'ach.weekly-warrior.title': 'Guerrero Semanal',
    'ach.weekly-warrior.desc': 'Alcanza una racha de 7 días',
    'ach.fortnight-fanatic.title': 'Fanático Quincenal',
    'ach.fortnight-fanatic.desc': 'Alcanza una racha de 14 días',
    'ach.monthly-legend.title': 'Leyenda Mensual',
    'ach.monthly-legend.desc': 'Alcanza una racha de 30 días',
    'ach.quarterly-king.title': 'Rey Trimestral',
    'ach.quarterly-king.desc': 'Alcanza una racha de 90 días',
    'ach.sports-fan.title': 'Fan de Deportes',
    'ach.sports-fan.desc': 'Juega 5 juegos de Deportes',
    'ach.action-novice.title': 'Novato de Acción',
    'ach.action-novice.desc': 'Juega 5 juegos de Acción',
    'ach.action-expert.title': 'Experto en Acción',
    'ach.action-expert.desc': 'Juega 25 juegos de Acción',
    'ach.puzzle-novice.title': 'Novato en Puzzles',
    'ach.puzzle-novice.desc': 'Juega 5 juegos de Puzzle',
    'ach.puzzle-expert.title': 'Experto en Puzzles',
    'ach.puzzle-expert.desc': 'Juega 25 juegos de Puzzle',
    'ach.wealthy.title': 'Adinerado',
    'ach.wealthy.desc': 'Acumula 1,000 monedas',
    'ach.rich.title': 'Gran Apostador',
    'ach.rich.desc': 'Acumula 5,000 monedas',
    'ach.millionaire.title': 'Millonario',
    'ach.millionaire.desc': 'Acumula 10,000 monedas',
    'ach.collector.title': 'Coleccionista',
    'ach.collector.desc': 'Compra 3 artículos de la tienda',
    'ach.hoarder.title': 'Acumulador',
    'ach.hoarder.desc': 'Compra 10 artículos de la tienda',
    'level.5.title': 'Explorador Novato',
    'level.10.title': 'Aprendiz de Jugador',
    'level.25.title': 'Veterano Experimentado',
    'level.50.title': 'Maestro de Arcade',
    'level.75.title': 'Gran Campeón',
    'level.100.title': 'Estado Legendario',
    'level.200.title': 'Entidad Mítica',
    'level.300.title': 'Ser Divino',
    'level.400.title': 'Señor Cósmico',
    'level.500.title': 'Creador Universal',
    'quest.daily-play-3.title': 'Calentamiento',
    'quest.daily-play-3.desc': 'Juega 3 juegos hoy',
    'quest.daily-play-10.title': 'Maratón',
    'quest.daily-play-10.desc': 'Juega 10 juegos hoy',
    'quest.daily-action-2.title': 'Héroe de Acción',
    'quest.daily-action-2.desc': 'Juega 2 juegos de Acción hoy',
    'quest.daily-puzzle-2.title': 'Maestro de Puzzles',
    'quest.daily-puzzle-2.desc': 'Juega 2 juegos de Puzzle hoy',
    'quest.weekly-play-25.title': 'Guerrero de Fin de Semana',
    'quest.weekly-play-25.desc': 'Juega 25 juegos esta semana',
    'quest.weekly-streak-5.title': 'Jugador Constante',
    'quest.weekly-streak-5.desc': 'Alcanza una racha de 5 días',
    'quest.weekly-action-10.title': 'Fanático de Acción',
    'quest.weekly-action-10.desc': 'Juega 10 juegos de Acción esta semana',
    'quest.weekly-puzzle-10.title': 'Cerebro Grande',
    'quest.weekly-puzzle-10.desc': 'Juega 10 juegos de Puzzle esta semana',
    'profile.title': 'Perfil',
    'profile.lvl': 'Nivel',
    'profile.xp': 'XP',
    'profile.streak': 'Racha Actual',
    'profile.coins': 'Monedas Totales',
    'profile.played': 'Juegos Jugados',
    'profile.daily': 'Recompensa Diaria',
    'profile.claim': 'Reclamar Ahora',
    'profile.claimed': 'Reclamado',
    'profile.skins': 'Skins Activas',
    'profile.snake': 'Neon Snake',
    'profile.snake.desc': 'Selecciona tu skin equipada para el juego Snake.',
    'profile.badges': 'Insignias de Logros',
    'profile.badges.none': 'Sin Insignias Aún',
    'profile.badges.none.desc': '¡Juega juegos y completa logros para ganar insignias!',
    'profile.redeem': 'Canjear Código',
    'profile.data': 'Gestión de Datos',
    'profile.export': 'Exportar Partida',
    'profile.export.desc': 'Exporta tus datos guardados para mantener tu progreso si alojas este sitio web en otro lugar.',
    'profile.import': 'Importar Partida',
    'profile.save': 'Guardar Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.prestige': 'Prestigio',
    'profile.owner': 'Dueño',
    'profile.admin': 'Admin',
    'profile.days': 'Días',
    'profile.multiplier': 'MULTIPLICADOR',
    'header.lvl': 'NIVEL',
    'header.coins': 'Monedas',
    'header.streak': 'Racha Diaria',
    'header.multiplier': 'Multiplicador',
    'header.rewards': 'Click para Recompensas',
    'header.roadmap': 'Hoja de Ruta',
    'header.quests': 'Misiones',
    'header.achievements': 'Logros',
    'header.store': 'Tienda',
    'header.profile': 'Perfil',
    'lang.english': 'English',
    'lang.spanish': 'Español (MX)',
    'roadmap.title': 'Hoja de Ruta de Progresión',
    'roadmap.desc': 'Sube de nivel para desbloquear recompensas y títulos exclusivos.',
    'roadmap.current': 'Nivel Actual',
    'roadmap.next': 'Siguiente Nivel',
    'roadmap.prestige.avail': '¡Prestigio Disponible!',
    'roadmap.prestige.desc': 'Reinicia tu nivel a 1 y gana un rango de Prestigio.',
    'roadmap.prestige.confirm': '¿Estás seguro de que quieres hacer Prestigio? ¡Esto reiniciará tu nivel y XP a 1, pero ganarás un rango de Prestigio!',
    'roadmap.prestige.now': 'Prestigio Ahora',
    'roadmap.level': 'Nivel',
    'roadmap.claim': 'Reclamar Recompensa',
    'roadmap.claimed': 'Reclamado',
    'roadmap.locked': 'Bloqueado',
    'daily.title': 'Recompensas Diarias',
    'daily.desc': '¡Mantén tu racha viva para multiplicar tus monedas diarias!',
    'daily.streak': 'Racha Actual',
    'daily.multiplier': 'Multiplicador Actual',
    'daily.claim': 'Reclamar Recompensa Diaria',
    'daily.claimed.msg': '¡Recompensa diaria reclamada!',
    'daily.tomorrow': '¡Vuelve mañana!',
    'daily.upcoming': 'Próximas Recompensas',
    'daily.day': 'Día',
    'daily.available': '¡Disponible Ahora!',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
